version: '3'
services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 5s
      retries: 30
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  nginx:
    build:
      context: ./.docker/nginx
    ports:
      - 80:80
